<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>App.Commands</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference PrivateAssets="All" Include="..\..\..\Exchange\Exchange.csproj" />
		<ProjectReference PrivateAssets="All" Include="..\..\Common\Common.Exceptions\Common.Exceptions.csproj" />
		<ProjectReference PrivateAssets="All" Include="..\..\Common\Common.Requests\Common.Requests.csproj" />
		<ProjectReference PrivateAssets="All" Include="..\Core\Core.Domain\Core.Domain.csproj" />
		<ProjectReference PrivateAssets="All" Include="..\Modules\Directories\Directories.Domain\Directories.Domain.csproj" />
		<ProjectReference PrivateAssets="All" Include="..\Modules\Receipt\Receipt.Domain\Receipt.Domain.csproj" />
		<ProjectReference PrivateAssets="All" Include="..\Modules\Shipment\Shipment.Domain\Shipment.Domain.csproj" />
	</ItemGroup>

</Project>
